//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSInventory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DrawerAmount
    {
        public int d_id { get; set; }
        public Nullable<int> Drawer_amount { get; set; }
    }
}
