//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSInventory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales_Detail
    {
        public Nullable<int> Sale_Id { get; set; }
        public Nullable<long> Item_No { get; set; }
        public Nullable<int> Item_Quantity { get; set; }
        public Nullable<int> Price { get; set; }
        public string Saleperson { get; set; }
        public int id { get; set; }
        public Nullable<System.DateTime> Sale_Date { get; set; }
    }
}
