//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSInventory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salespersondetail
    {
        public int id { get; set; }
        public string Date { get; set; }
        public string Salesperson { get; set; }
        public Nullable<int> Totalsale { get; set; }
        public Nullable<int> Loginammount { get; set; }
        public Nullable<int> Logoutammount { get; set; }
        public string Time { get; set; }
        public string Counter { get; set; }
    }
}
