//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSInventory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock_Detail
    {
        public int Sid { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<long> Itemno { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Time { get; set; }
    }
}
